### PR TITLE
Add an HasEndpoint instance for AuthProtect

### PR DESCRIPTION
**Pull request by vendethiel**
Thanks for the package. It was just missing this instance which we use.

### CODE REVIEW

**Comment by vendethiel** [comment]
Also, is there a reason Servant is constrained to < 0.20 ?

**Review by worm2fed — APPROVED** [review]
LGTM, thanks for your PR

**Comment by worm2fed** [comment]
@vendethiel 
CI is failing, will fix that later

> Also, is there a reason Servant is constrained to < 0.20 ?

Most likely it will work well with 0.20, if you need that - we can move upper bound and add a support for higher ghc version

**Comment by vendethiel** [comment]
> Most likely it will work well with 0.20, if you need that - we can move upper bound and add a support for higher ghc version

Work codebase is not dependent on newer Servant, so it's not a priority, I just wanted to know.
Thanks for your answers.

**Comment by worm2fed** [comment]
@vendethiel you're welcome to merge

**Comment by vendethiel** [comment]
I don't think I can merge PRs here

**Comment by vendethiel** [comment]
Thank you!

**Pull request merged**
